	
	CREATE TABLE STUDENT(
	STUDENTID NUMBER (10) NOT NULL PRIMARY KEY,
	STUDENTNAME NUMBER (10) NOT NULL,
	DEGREEID NUMBER (10) NOT NULL,
	SUBJECTID NUMBER (10) NOT NULL,
  constraint fk_StudentDID FOREIGN KEY (DEGREEID) REFERENCES DEGREE_CLASS(DEGREEID),
	constraint fk_StudentSUBID FOREIGN KEY (SUBJECTID) REFERENCES SUBJECT(SUBJECTID)
	);

	CREATE TABLE DEGREE_CLASS(
	DEGREEID NUMBER (10) NOT NULL PRIMARY KEY,
	DEGREECLASS VARCHAR (10) NOT NULL
	);
	
	CREATE TABLE EXAM(
	EXAMID NUMBER (10) NOT NULL PRIMARY KEY,
	MODNUM VARCHAR (10) NOT NULL,
	SYID NUMBER (10) NOT NULL,
	constraint fk_ExamMODNUM FOREIGN KEY (MODNUM) REFERENCES MODULE(MODNUM),
	constraint fk_ExamSYID FOREIGN KEY (SYID) REFERENCES SEM_YEAR(SYID)
	);

	CREATE TABLE EXAM_DET(
	EXAMID NUMBER (10) NOT NULL,
	AUTHOR VARCHAR (10)  NOT NULL,
	ATTEMPT NUMBER (10) NOT NULL,
	WEIGHTING VARCHAR (10) NOT NULL,
	OUTCOME NUMBER (10) NOT NULL,
	MARKS NUMBER (10)NOT NULL,
	QID NUMBER (10) NOT NULL,
	constraint fk_Exam_ID FOREIGN KEY (EXAMID) REFERENCES EXAM(EXAMID),
	constraint fk_Exam_QID FOREIGN KEY (QID) REFERENCES QUESTIONS(QID)		
	);

	CREATE TABLE SEM_YEAR(
	SYID NUMBER (10) NOT NULL PRIMARY KEY ,
	SEMESTER VARCHAR (10) NOT NULL,
	YID NUMBER (10) NOT NULL,
	constraint fkSEM_YEARYID FOREIGN KEY (YID) REFERENCES YEAR(YID)
	);

	CREATE TABLE YEAR(
	YID NUMBER (10) NOT NULL PRIMARY KEY ,       
	YEAR VARCHAR (10) NOT NULL
	);

	CREATE TABLE SUBJECT(
	SUBJECTID NUMBER (10) NOT NULL PRIMARY KEY,
	SUBJECTNAME VARCHAR (10)NOT NULL
	);	

	CREATE TABLE MODULE(
	MODNUM NUMBER (10) NOT NULL PRIMARY KEY ,
	MODNAME VARCHAR (10) NOT NULL

	);	

	CREATE TABLE COURSEWORK(
	CWID      NUMBER (10) NOT NULL PRIMARY KEY,
	MODNUM VARCHAR (10) NOT NULL,
	SYID       NUMBER (10) NOT NULL,
	LID       NUMBER (10) NOT NULL,
        constraint fk_COURSEWORKMODNUM FOREIGN KEY (MODNUM) REFERENCES MODULE(MODNUM),
	constraint fk_COURSEWORKSYID FOREIGN KEY (SYID) REFERENCES SEM_YEAR(SYID),
        constraint fk_COURSEWORKLID FOREIGN KEY (LID) REFERENCES LECTURER(LID)
	);

	CREATE TABLE COURSEWORK_MARKS(
	CWID      NUMBER (10) NOT NULL ,
	WEIGHTING VARCHAR (10) NOT NULL,
	YID       NUMBER (10) NOT NULL,
	OUTCOME   VARCHAR (10)  NOT NULL,
   	constraint fk_COURSEWORK_MARKSCWID FOREIGN KEY (CWID) REFERENCES COURSEWORK(CWID),
	constraint fk_COURSEWORK_MARKSYID FOREIGN KEY (YID) REFERENCES YEAR(YID)
	);

	CREATE TABLE DEPT(
	DID NUMBER (10) NOT NULL PRIMARY KEY,
	DEPTNAME VARCHAR (10) NOT NULL
	);	


	CREATE TABLE STAFF(
	STAFFID NUMBER (10) NOT NULL PRIMARY KEY,
	STAFFNAME VARCHAR (10) NOT NULL,
	DID NUMBER (10) NOT NULL,
	constraint fkSTAFFDID FOREIGN KEY (DID) REFERENCES DEPT(DID)
	);

	CREATE TABLE GRADEREPORT(
	STUDENTID NUMBER (10) NOT NULL,
	SUBJECTID NUMBER (10)  NOT NULL,
	constraint fkGRADEREPORTSTUDENTID FOREIGN KEY (STUDENTID) REFERENCES STUDENT(STUDENTID),
	constraint fkGRADEREPORTSUBJECTID FOREIGN KEY (SUBJECTID) REFERENCES SUBJECT(SUBJECTID)
	);	

	CREATE TABLE SUBINMOD(
	SUBJECTID NUMBER (10) NOT NULL,
	MODNUM NUMBER (10) NOT NULL,
	OVERALLMARK NUMBER(10) NOT NULL,
	constraint fk_SUBINMODSUBJECTID FOREIGN KEY (SUBJECTID) REFERENCES SUBJECT(SUBJECTID),
	constraint fk_SUBINMODMODNUM FOREIGN KEY (MODNUM) REFERENCES MODULE(MODNUM)
	);

	CREATE TABLE LECTURER(
	LID NUMBER (10) NOT NULL PRIMARY KEY,
	LNAME NUMBER (10) NOT NULL,
	MODNUM NUMBER(10) NOT NULL,

        constraint fk_LECTURERMODNUM FOREIGN KEY (MODNUM) REFERENCES MODULE(MODNUM)
	);	

	CREATE TABLE QUESTIONS(
	QID NUMBER (10) NOT NULL PRIMARY KEY ,
	MARKS NUMBER(10) NOT NULL
	);
	
		
	

	
