      DROP VIEW SOMECRAP;
      DROP VIEW CRAP;
      DROP VIEW LNAME_MODNAME;	
	

	CREATE VIEW crap AS
            SELECT *
            FROM STUDENT
            WHERE STUDENTID IN (SELECT STUDENTID FROM GRADEREPORT)
       WITH CHECK OPTION;

	
	CREATE VIEW somecrap AS
	SELECT MODNAME 
	FROM MODULE
	WHERE MODNUM IN (SELECT MODNUM FROM SUBINMOD WHERE OVERALLMARK=100);

	
	CREATE VIEW LNAME_MODNAME (LNAME, MODNAME) AS
			SELECT LNAME, MODNAME
			FROM LECTURER, MODULE
			WHERE LECTURER.MODNUM = MODULE.MODNUM;
	
	 
	SELECT * FROM somecrap;
	
	SELECT * FROM crap;
	
	SELECT * FROM LNAME_MODNAME ;

